### ISSUE TITLE
Use zero-inflated reconstruction loss

### ISSUE THREAD

**Issue by chrisprobert** [greenelab/czi-rfa#11]
Single-cell RNA-seq data is sparse/zero-inflated. There are several works [1-3] showing advantages of modeling zero-inflated distances between cells over L-1/L-2 distances.

For the VAE in aim 1, I expect that using zero inflated loss rather than euclidean reconstruction loss would work significantly better.

[1] https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0805-z
[2] https://arxiv.org/abs/1610.05857
[3] https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1188-0

**Comment by cgreene** [comment]
Closed with #13. Thanks a ton @chrisprobert for the suggestion! I have included your name + a citation to this issue in the proposal. Please let me know by Sunday if you would prefer that I remove it.

**Comment by gwaybio** [comment]
A [recent arxiv paper](https://arxiv.org/abs/1709.02082) describes this idea, with code implemented in tensorflow [here](https://github.com/YosefLab/ZINB-VAE).

Note, the model is evaluated with [720 genes](https://github.com/YosefLab/ZINB-VAE/blob/master/zinb-vae.py#L87)

**Comment by chrisprobert** [comment]
Looks awesome!
