### ISSUE TITLE
Aim 3 - Arjun's Data and Experimental Design

### ISSUE THREAD

**Issue by gwaybio** [greenelab/czi-rfa#5]
As @cgreene noted in #3 

> We will need more detail from Arjun to provide an example. I think you should make a hypothetical example of the latent space arithmetic experimental design. What about doing it as single cell data + bulk perturbation & comparing to single cell + perturbation? That seems like the cleanest design to test your hypothesis.

We will use this issue to discuss the nature of the data and experimental design to test the hypothesis:

**that the latent space will preserve vector arithmetic operations between state transitions within benchmark perturbation expression datasets.**

The issue can be closed once the experimental design is updated in aim 3.

**Comment by gwaybio** [comment]
It appears that the data will consist of homogenized cell-types under various perturbations.

The purpose/assumption being that under various different stresses, the essence of a "cell-type" will become clear. The cell-type essence features will remain invariant and provide the essential representations for a manifold learning algorithm (i.e. VAE, GAN) to characterize.

**Comment by cgreene** [comment]
Tried to more clearly note alternative datasets also work in #15
